### Generics for ppstat. 

setGeneric("coefficients<-",function(model,value) standardGeneric("coefficients<-"))
setGeneric("computeLinearPredictor",function(model,...) standardGeneric("computeLinearPredictor"))
setGeneric("computeBasis",function(model,form,...) standardGeneric("computeBasis"))

setGeneric("computeMinusLogLikelihood",function(model,coefficients=NULL,...) standardGeneric("computeMinusLogLikelihood"))
setGeneric("computeDMinusLogLikelihood",function(model,coefficients=NULL,...) standardGeneric("computeDMinusLogLikelihood"))
setGeneric("computeDDMinusLogLikelihood",function(model,coefficients=NULL,...) standardGeneric("computeDDMinusLogLikelihood"))
setGeneric("computeModelMatrix",function(model,evaluationPositions=NULL,...) standardGeneric("computeModelMatrix"))
setGeneric("computeRecurrenceMatrix",function(model,evaluationPositions=NULL,A=1000,...) standardGeneric("computeRecurrenceMatrix"))
setGeneric("computeVar",function(model,...) standardGeneric("computeVar"))
setGeneric("formula<-",function(model,value) standardGeneric("formula<-"))
setGeneric("getModelMatrix",function(model,col,...) standardGeneric("getModelMatrix"))
setGeneric("getModelMatrixEnv",function(model,...) standardGeneric("getModelMatrixEnv"))
setGeneric("getProcessData",function(model,...) standardGeneric("getProcessData"))
setGeneric("getBasis",function(model,term,...) standardGeneric("getBasis"))
setGeneric("getLinearFilter",function(model,se,nr,...) standardGeneric("getLinearFilter"))
setGeneric("ppmFit",function(model,control=list(),...) standardGeneric("ppmFit"))
setGeneric("setBasis<-",function(model,term,value) standardGeneric("setBasis<-"))
setGeneric("setModelMatrix<-",function(model,value) standardGeneric("setModelMatrix<-"))
setGeneric("setModelMatrixEnv<-",function(model,value) standardGeneric("setModelMatrixEnv<-"))
setGeneric("setProcessData<-",function(model,value) standardGeneric("setProcessData<-"))
