### Generics for ppstat. 

setGeneric("computeLinearPredictor",function(model,...) standardGeneric("computeLinearPredictor"))
setGeneric("computeMinusLogLikelihood",function(model,coefficients=NULL,...) standardGeneric("computeMinusLogLikelihood"))
setGeneric("computeDMinusLogLikelihood",function(model,coefficients=NULL,...) standardGeneric("computeDMinusLogLikelihood"))
setGeneric("computeDDMinusLogLikelihood",function(model,coefficients=NULL,...) standardGeneric("computeDDMinusLogLikelihood"))
setGeneric("computeModelMatrix",function(model,evaluationPositions=NULL,...) standardGeneric("computeModelMatrix"))
setGeneric("computeRecurrenceMatrix",function(model,evaluationPositions=NULL,A=1000,...) standardGeneric("computeRecurrenceMatrix"))
setGeneric("getModelMatrix",function(model,...) standardGeneric("getModelMatrix"))
setGeneric("getLinearFilter",function(model,se,nr,...) standardGeneric("getLinearFilter"))
setGeneric("getProcessData",function(model,...) standardGeneric("getProcessData"))
setGeneric("coefficients<-",function(model,value,...) standardGeneric("coefficients<-"))
setGeneric("formula<-",function(model,value,...) standardGeneric("formula<-"))
setGeneric("glppmFit",function(model,initPar,control=list(),...) standardGeneric("glppmFit"))
setGeneric("computeVar",function(model,...) standardGeneric("computeVar"))
