### Generics for ppstat. 

setGeneric("anticipating", function(model, ...) standardGeneric("anticipating"))
setGeneric("coefficients<-", function(model, value) standardGeneric("coefficients<-"))
setGeneric("computeLinearPredictor", function(model, ...) standardGeneric("computeLinearPredictor"))
setGeneric("computeBasis", function(model, form, ...) standardGeneric("computeBasis"))
setGeneric("computeMinusLogLikelihood", function(model, coefficients=NULL, ...) standardGeneric("computeMinusLogLikelihood"))
setGeneric("computeDMinusLogLikelihood", function(model, coefficients=NULL, ...) standardGeneric("computeDMinusLogLikelihood"))
setGeneric("computeDDMinusLogLikelihood", function(model, coefficients=NULL, ...) standardGeneric("computeDDMinusLogLikelihood"))
setGeneric("computeModelMatrix", function(model, evaluationPositions=NULL, ...) standardGeneric("computeModelMatrix"))
setGeneric("computeRecurrenceMatrix", function(model, evaluationPositions = NULL, A = 1000, ...) standardGeneric("computeRecurrenceMatrix"))
setGeneric("computeWeights", function(model, coefficients=NULL, ...) standardGeneric("computeWeights"))
setGeneric("computeWorkingResponse", function(model, coefficients=NULL, ...) standardGeneric("computeWorkingResponse"))
setGeneric("computeVar", function(model, ...) standardGeneric("computeVar"))
setGeneric("formula<-", function(model,value) standardGeneric("formula<-"))
setGeneric("getBasis", function(model, term,...) standardGeneric("getBasis"))
setGeneric("getInformation", function(model, ...) standardGeneric("getInformation"))
setGeneric("getLinearFilter", function(model, ...) standardGeneric("getLinearFilter"))
setGeneric("getModelMatrix", function(model, col,...) standardGeneric("getModelMatrix"))
setGeneric("getModelMatrixEnv", function(model, ...) standardGeneric("getModelMatrixEnv"))
setGeneric("IWLS", function(model, control, ...) standardGeneric("IWLS"))
setGeneric("processData", function(model, ...) standardGeneric("processData"))
setGeneric("ppmFit", function(model, control=list(), ...) standardGeneric("ppmFit"))
setGeneric("response", function(model, ...) standardGeneric("response"))
setGeneric("setBasis<-", function(model,term,value) standardGeneric("setBasis<-"))
setGeneric("setModelMatrix<-", function(model, value) standardGeneric("setModelMatrix<-"))
setGeneric("setModelMatrixEnv<-", function(model, value) standardGeneric("setModelMatrixEnv<-"))
setGeneric("stepInformation", function(model, ...) standardGeneric("stepInformation"))
setGeneric("processData<-", function(model, value) standardGeneric("processData<-"))
setGeneric("termPlot", function(model, ...) standardGeneric("termPlot"))
